# Релиз бинарников nekkus-net в GitHub Releases.
# Триггер: git tag v* и push (например v0.1.0).
# В CI используется matrix: каждый раннер собирает только свою ОС (см. override-файлы).

project_name: nekkus-net

builds:
  - id: nekkus-net
    main: ./cmd
    binary: nekkus-net
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0

archives:
  - id: default
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    wrap_in_directory: '{{ "com.nekkus.net" }}'
    # Без дефолтных LICENSE/README; манифест из release_assets (не в .gitignore)
    files:
      - none*
      - src: release_assets/manifest.json
        dst: .

release:
  github:
    owner: GalitskyKK
    name: nekkus-net
  name_template: "v{{ .Version }}"
