# macos-latest = arm64. CGO для webview/systray; darwin/amd64 не собираем.
builds:
  - id: nekkus-net
    main: ./cmd
    binary: nekkus-net
    goos:
      - darwin
    goarch:
      - arm64
    env:
      - CGO_ENABLED=1
