# Ubuntu = amd64. Webview/systray — CGO, только нативная сборка.
builds:
  - id: nekkus-net
    main: ./cmd
    binary: nekkus-net
    goos:
      - linux
    goarch:
      - amd64
    env:
      - CGO_ENABLED=1
