# Windows runner = amd64. CGO для webview/systray.
builds:
  - id: nekkus-net
    main: ./cmd
    binary: nekkus-net
    goos:
      - windows
    goarch:
      - amd64
    env:
      - CGO_ENABLED=1
