project_name: nekkus-net

builds:
  - id: nekkus-net
    main: ./cmd
    binary: nekkus-net
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0

archives:
  - id: default
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    wrap_in_directory: com.nekkus.net
    files:
      - src: release_assets/manifest.json
        dst: .
        strip_parent: true

release:
  github:
    owner: GalitskyKK
    name: nekkus-net
  name_template: "v{{ .Version }}"