# Оставляем только windows для раннера windows.
builds:
  - id: nekkus-net
    main: ./cmd
    binary: nekkus-net
    goos:
      - windows
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
